[[main]]
  identifier = "posts"
  name = "Home"
  url = ""
  weight = 1

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 2

[[main]]
  parent = "about"
  name = "Website"
  url = "about"

[[main]]
  parent = "about"
  name = "Me"
  url = "resume"

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 3

[[main]]
    name = "Sections"
    url = "posts"
    weight = 4

[[main]]
    name = "TL;DR"
    url = "/categories/TLDR"
    parent = "Sections"

[[main]]
    name = "How To"
    url = "/categories/howto"
    parent = "Sections"

[[main]]
  identifier = "searx"
  name = "Searx!"
  url = "https://searx.niceadsl.xyz"
  weight = 6

