[[main]]
  identifier = "posts"
  name = "Inicio"
  url = ""
  weight = 1

[[main]]
  identifier = "sobre"
  name = "Sobre"
  url = "about"
  weight = 2

[[main]]
  parent = "sobre"
  name = "Web"
  url = "about"

[[main]]
  parent = "sobre"
  name = "Mi"
  url = "resume"

[[main]]
  identifier = "archive"
  name = "Archivo"
  url = "archive"
  weight = 3

[[main]]
    name = "Secciones"
    url = "posts"
    weight = 4

[[main]]
    name = "Mucho Texto"
    url = "/categories/TLDR"
    parent = "Secciones"

[[main]]
    name = "Por qué"
    url = "/categories/why"
    parent = "Secciones"

[[main]]
    name = "Cómo"
    url = "/categories/howto"
    parent = "Secciones"


#[[main]]
    #name = "LeanMind"
    #url = "/categories/leanmind"
    #parent = "Secciones"

[[main]]
  identifier = "showcase"
  name = "Proyectos!"
  url = "showcase"
  weight = 7

[[main]]
  parent = "showcase"
  identifier = "searx"
  name = "Searx!"
  url = "showcase/searx"

[[main]]
  parent = "showcase"
  identifier = "nextcloud"
  name = "NextCloud"
  url = "showcase/nextcloud"
